postgres:
  host: localhost
  port: 5432
  user: keyhub-local
  password: keyhub
  database: keyhub
sentry:
  dsn: ""
env: "local"
auth:
  google:
    client_id:
    client_secret:
console:
  organization_id: "550e8400-e29b-41d4-a716-446655440000"
  organization_key: "org_key_example_12345"
