postgres:
  host: localhost
  port: 5432
  user: keyhub-local
  password: keyhub
  database: keyhub
sentry:
  dsn: ""
env: "local"
frontend_url:
  app: "http://localhost:5173"
  console: "http://localhost:5174"
auth:
  google:
    client_id:
    client_secret:
    redirect_uri:
console:
  organization_id:
  organization_key:
  jwt_secret:
