postgres:
  host: localhost
  port: 5432
  user: keyhub-local
  password: keyhub
  database: keyhub
sentry:
  dsn: ""
env: "local"
auth:
  google:
    client_id:
    client_secret:
console:
  organization_id:
  organization_key:
