name: TS Lint

on:
  push:

jobs:
  ts-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 10
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"
          cache-dependency-path: "frontend/*/pnpm-lock.yaml"
      - name: Install dependencies (app)
        run: pnpm install --frozen-lockfile
        working-directory: frontend/app
      - name: Install dependencies (console)
        run: pnpm install --frozen-lockfile
        working-directory: frontend/console
      - name: Lint (app)
        run: pnpm run lint
        working-directory: frontend/app
      - name: Lint (console)
        run: pnpm run lint
        working-directory: frontend/console
      - name: Format check (app)
        run: pnpm run fmt
        working-directory: frontend/app
      - name: Format check (console)
        run: pnpm run fmt
        working-directory: frontend/console
      - run: git diff --exit-code
